---
apiVersion: v1
kind: Namespace
metadata:
  name: watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: watch-view
subjects:
  - kind: ServiceAccount
    name: default
    namespace: watch
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: watch-${TYPE}
  labels:
    app: watch
  namespace: watch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: watch
  template:
    metadata:
      labels:
        app: watch
    spec:
      containers:
      - name: watch
        image: ${IMAGE}
        command:
          - /go/bin/main
