[[override]]
  name = "github.com/Azure/go-autorest"
  version = "v11.4.0"

[[override]]
  name = "k8s.io/kubernetes"
  version = "v1.13.1"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.13.1"

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.13.1"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.13.1"

[[override]]
  name = "k8s.io/apiserver"
  version = "kubernetes-1.13.1"
